services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_volume:/prometheus
  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
  springbootapp:
    image: employment-monitored-spring-boot-app
    container_name: boot
    ports:
      - 8080:8080
    restart: unless-stopped
volumes:
  prometheus_volume:
